### ISSUE TITLE
Formulário nao está enviando mensagens

### ISSUE THREAD

**Issue by everton137** [AppCivico/libre-api#3]
Tentei enviar uma mensagem via formulário de contato e recebi a seguinte mensagem: "Não foi possível enviar sua mensagem!"

Será que foi porque preenchi o telefone no formato internacional? +XX (código do país) YYYY (número do telefone)

**Comment by robsonsobral** [comment]
Obrigado por reportar.

[Corrigido!](https://github.com/AppCivico/libre-web/commit/0f8758c6e859e7a3c5decf73cb177edbe82ac4c0)
